# Generated by Django 5.0.3 on 2024-09-06 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='link_plant.profile'),
        ),
    ]
